import mongoose from "mongoose";
import dotenv from "dotenv";
import Product from "../models/Product.js";
import MerchantRule from "../models/MerchantRule.js";
dotenv.config();

const products = [
  {
    name: "Red Running Shoe",
    price: 2499,
    category: "footwear",
    stock: 15,
    description: "Lightweight performance running shoe with breathable mesh upper, built for daily training.",
    style: "sport",
    color: "red",
    material: "mesh",
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
  },
  {
    name: "Black Formal Oxford Shoe",
    price: 3299,
    category: "footwear",
    stock: 10,
    description: "Classic leather oxford shoe, polished finish, suited for formal and office wear.",
    style: "formal",
    color: "black",
    material: "leather",
    imageUrl: "https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=400",
  },
  {
    name: "White Canvas Sneaker",
    price: 1899,
    category: "footwear",
    stock: 20,
    description: "Minimal white canvas sneaker, casual everyday wear, pairs well with most outfits.",
    style: "casual",
    color: "white",
    material: "canvas",
    imageUrl: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=400",
  },
  {
    name: "Cotton Ankle Socks (Pack of 3)",
    price: 299,
    category: "accessories",
    stock: 50,
    description: "Breathable cotton ankle socks, pack of 3, suited for sport and daily wear shoes.",
    style: "sport",
    color: "white",
    material: "cotton",
    imageUrl: "https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=400",
  },
  {
    name: "Leather Shoe Polish Kit",
    price: 449,
    category: "accessories",
    stock: 30,
    description: "Premium shoe polish and brush kit for maintaining leather formal footwear.",
    style: "formal",
    color: "neutral",
    material: "wax",
    imageUrl: "https://images.unsplash.com/photo-1610386455459-2d0f16c1e478?w=400",
  },
  {
    name: "Blue Denim Jacket",
    price: 3499,
    category: "outerwear",
    stock: 10,
    description: "Classic mid-wash denim jacket, casual layering piece for everyday wear.",
    style: "casual",
    color: "blue",
    material: "denim",
    imageUrl: "https://images.unsplash.com/photo-1543087903-1ac2ec7aa8c5?w=400",
  },
  {
    name: "Black Formal Blazer",
    price: 5999,
    category: "outerwear",
    stock: 8,
    description: "Tailored black blazer for formal occasions, weddings, and office events.",
    style: "formal",
    color: "black",
    material: "polyester blend",
    imageUrl: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400",
  },
  {
    name: "Grey Wool Overcoat",
    price: 6499,
    category: "outerwear",
    stock: 6,
    description: "Heavy wool overcoat for cold weather, formal and semi-formal styling.",
    style: "formal",
    color: "grey",
    material: "wool",
    imageUrl: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=400",
  },
  {
    name: "Wireless Earbuds",
    price: 1999,
    category: "electronics",
    stock: 20,
    description: "Compact true wireless earbuds with noise isolation and 24-hour battery case.",
    style: "everyday",
    color: "black",
    material: "plastic",
    imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400",
  },
  {
    name: "Over-Ear Headphones",
    price: 3999,
    category: "electronics",
    stock: 12,
    description: "Over-ear headphones with deep bass and active noise cancellation, for travel and daily commute.",
    style: "everyday",
    color: "black",
    material: "plastic",
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
  },
  {
    name: "Phone Cover",
    price: 399,
    category: "accessories",
    stock: 40,
    description: "Shockproof silicone phone cover, slim fit, available for common phone models.",
    style: "everyday",
    color: "black",
    material: "silicone",
    imageUrl: "https://images.unsplash.com/photo-1541877590-a1885dd75f0d?w=400",
  },
  {
    name: "Wireless Charging Pad",
    price: 899,
    category: "electronics",
    stock: 25,
    description: "Fast wireless charging pad compatible with most smartphones, compact desk-friendly design.",
    style: "everyday",
    color: "white",
    material: "plastic",
    imageUrl: "https://images.unsplash.com/photo-1591290619762-b0a3d3e5c25b?w=400",
  },
  {
    name: "Cotton T-Shirt",
    price: 699,
    category: "topwear",
    stock: 35,
    description: "Soft breathable cotton t-shirt, everyday casual wear, regular fit.",
    style: "casual",
    color: "white",
    material: "cotton",
    imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",
  },
  {
    name: "Formal White Shirt",
    price: 1299,
    category: "topwear",
    stock: 18,
    description: "Crisp formal white shirt, slim fit, suited for office and formal events.",
    style: "formal",
    color: "white",
    material: "cotton blend",
    imageUrl: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400",
  },
  {
    name: "Leather Belt",
    price: 799,
    category: "accessories",
    stock: 22,
    description: "Genuine leather belt with metal buckle, pairs well with formal trousers.",
    style: "formal",
    color: "black",
    material: "leather",
    imageUrl: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=400",
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI);
  await Product.deleteMany({});
  await Product.insertMany(products);
  await MerchantRule.deleteMany({});
  await MerchantRule.create({ maxOrderValue: 8000, dailySpendCap: 20000 });
  console.log(`Seeded ${products.length} products + merchant rules`);
  process.exit();
}
seed();